name=printfx
version=1.0.0
author=Andre M. Maree / KSS Technologies
maintainer=Andre M. Maree / KSS Technologies
sentence=ESP-IDF component bridge.
paragraph=Accessing my external component.
category=Uncategorized
url=
architectures=all
